# values.yaml

upstream:
  url: "wordpress-service"  # The service name of the application to proxy
  port: 80                 # The port of the upstream service

replicaCount: 1           # Number of replicas for the nginx-proxy deployment

image:
  repository: hibajameel/nginx-proxy
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP         # The type of service (ClusterIP, NodePort, LoadBalancer)
  port: 80                # The port exposed by the service

labels:
  id: "C0910893"
  app: "nginx-proxy"
  env: "dev"

resources:                # Optional: Specify resource limits/requests for containers
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"





