apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: proxy
  labels:
    id: "C0910893"
    app: "nginx-proxy"
    env: "dev"
spec:
  replicas: 1
  selector:
    matchLabels:
      id: "C0910893"
      app: "nginx-proxy"
      env: "dev"
  template:
    metadata:
      labels:
        id: "C0910893"
        app: "nginx-proxy"
        env: "dev"
    spec:
      containers:
      - name: nginx-proxy
        image: hibajameel/nginx-proxy:latest
        ports:
        - containerPort: 80


