apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: proxy
  labels:
    id: "C0910893"
    app: "nginx-proxy"
    env: "dev"
spec:
  selector:
    id: "C0910893"
    app: "nginx-proxy"
    env: "dev"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


